/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package studio.codable.bitriser.util.networking.apis

import retrofit2.http.GET
import retrofit2.http.Headers
import studio.codable.bitriser.util.networking.models.ServiceStandardErrorRespModel
import studio.codable.bitriser.util.networking.models.V0AppleAPICredentialsListResponse

@JvmSuppressWildcards
interface AppleApiCredentialsApi {
    /**
     * List Apple API credentials for a specific user
     * List Apple API credentials for a specific Bitrise user
     * The endpoint is owned by defaultname service owner
     * @param userSlug User slug (required)
     */
    @Headers(
        "X-Operation-ID: apple-api-credential-list"
    )
    @GET("users/{user-slug}/apple-api-credentials")
    suspend fun appleApiCredentialList(
        @retrofit2.http.Path("user-slug") userSlug: String
    ): V0AppleAPICredentialsListResponse
}
