/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package studio.codable.bitriser.util.networking.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property expiringRawLogUrl
 * @property generatedLogChunksNum
 * @property isArchived
 * @property logChunks
 * @property timestamp
 */
@JsonClass(generateAdapter = true)
data class V0BuildLogInfoResponseModel(
    @Json(name = "expiring_raw_log_url") @field:Json(name = "expiring_raw_log_url") var expiringRawLogUrl: String? = null,
    @Json(name = "generated_log_chunks_num") @field:Json(name = "generated_log_chunks_num") var generatedLogChunksNum: Int? = null,
    @Json(name = "is_archived") @field:Json(name = "is_archived") var isArchived: Boolean? = null,
    @Json(name = "log_chunks") @field:Json(name = "log_chunks") var logChunks: List<V0BuildLogChunkItemResponseModel>? = null,
    @Json(name = "timestamp") @field:Json(name = "timestamp") var timestamp: String? = null
)
